version: '3.4'

services:
  webapp.gestao.api:
    image: ${DOCKER_REGISTRY-}webappgestaoapi
    build:
      context: .
      dockerfile: WebApp.Gestao.Api/Dockerfile
    
  database:
    image: postgres:latest
